<?xml version="1.0" encoding="UTF-8" standalone="no"?><definitions><types><propriétés><réputation>2</réputation><confiance>0</confiance><expérience>3</expérience><disponibilité>4</disponibilité><coût>5</coût><temps_de_réponse>6</temps_de_réponse><risques>6</risques><temps_moyen_de_représentation>1</temps_moyen_de_représentation></propriétés></types><message>definition of the data being communicated....</message><portType>set of operations...... </portType><binding>protocol and data format specification....</binding></definitions>